apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: default
spec:
  selector:
    app: account-service
    version: blue  # Initially point to the blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
